/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package main.android.demo.opentoksamples;

public final class R {
    public static final class attr {
    }

    public static final class color {
        public static final int black_grey = 0x7f040000;
        public static final int blue = 0x7f040001;
        public static final int color0_gradient = 0x7f040002;
        public static final int color1_gradient = 0x7f040003;
        public static final int dark_grey = 0x7f040004;
        public static final int grey = 0x7f040005;
        public static final int init_gradient = 0x7f040006;
        public static final int trans = 0x7f040007;
        public static final int trans_dark_grey = 0x7f040008;
        public static final int trans_white = 0x7f040009;
        public static final int white = 0x7f04000a;
    }

    public static final class drawable {
        public static final int archiving_off = 0x7f020000;
        public static final int archiving_on = 0x7f020001;
        public static final int audio_only = 0x7f020002;
        public static final int avatar = 0x7f020003;
        public static final int button_background = 0x7f020004;
        public static final int camera = 0x7f020005;
        public static final int headset = 0x7f020006;
        public static final int high_congestion = 0x7f020007;
        public static final int ic_launcher = 0x7f020008;
        public static final int mid_congestion = 0x7f020009;
        public static final int mute_pub = 0x7f02000a;
        public static final int mute_sub = 0x7f02000b;
        public static final int no_video = 0x7f02000c;
        public static final int publisher = 0x7f02000d;
        public static final int silhouette2 = 0x7f02000e;
        public static final int speaker_active = 0x7f02000f;
        public static final int unmute_pub = 0x7f020010;
        public static final int unmute_sub = 0x7f020011;
    }

    public static final class id {
        public static final int archiving = 0x7f080006;
        public static final int archivingbar = 0x7f08002d;
        public static final int archivingimg = 0x7f08002e;
        public static final int archivingstatus = 0x7f08002f;
        public static final int audioOnlyView = 0x7f080016;
        public static final int avatar = 0x7f080018;
        public static final int bottomcontainer = 0x7f080028;
        public static final int congestionIndicator = 0x7f080012;
        public static final int connectionStatus = 0x7f080009;
        public static final int divider = 0x7f080030;
        public static final int divider1 = 0x7f080031;
        public static final int divider2 = 0x7f08002a;
        public static final int endCall = 0x7f080004;
        public static final int fragment_pub_container = 0x7f08001b;
        public static final int fragment_pub_status_container = 0x7f08001c;
        public static final int fragment_sub_container = 0x7f08001a;
        public static final int fragment_sub_quality_container = 0x7f08001d;
        public static final int layoutPubFragment = 0x7f080000;
        public static final int layoutSubFragment = 0x7f08000a;
        public static final int layoutSubQualityFragment = 0x7f080010;
        public static final int line1 = 0x7f080008;
        public static final int line2 = 0x7f08000e;
        public static final int listview = 0x7f08001e;
        public static final int loadingSpinner = 0x7f080015;
        public static final int mainlayout = 0x7f080013;
        public static final int menu_settings = 0x7f080035;
        public static final int message = 0x7f080026;
        public static final int messageView = 0x7f080024;
        public static final int messagebox = 0x7f080023;
        public static final int mutePublisher = 0x7f080002;
        public static final int muteSubscriber = 0x7f08000c;
        public static final int pager = 0x7f080021;
        public static final int preview = 0x7f080025;
        public static final int publisherStatusWidget = 0x7f080005;
        public static final int publisherView = 0x7f080019;
        public static final int publisherWidget = 0x7f080001;
        public static final int publishermeter = 0x7f08002c;
        public static final int publishername = 0x7f08002b;
        public static final int publisherpicture = 0x7f080029;
        public static final int publisherview = 0x7f080020;
        public static final int scroller = 0x7f080022;
        public static final int sendMessageButton = 0x7f080027;
        public static final int statusLabel = 0x7f080007;
        public static final int subscriberAudioLevelWidget = 0x7f08000b;
        public static final int subscriberName = 0x7f08000d;
        public static final int subscriberStatusWidget = 0x7f080011;
        public static final int subscriberView = 0x7f080014;
        public static final int subscriberWidget = 0x7f08000f;
        public static final int subscribermeter = 0x7f080017;
        public static final int subscribername = 0x7f080033;
        public static final int subscriberpicture = 0x7f080032;
        public static final int subscriberview = 0x7f08001f;
        public static final int swapCamera = 0x7f080003;
        public static final int volume = 0x7f080034;
    }

    public static final class layout {
        public static final int layout_fragment_pub_control = 0x7f030000;
        public static final int layout_fragment_pub_status = 0x7f030001;
        public static final int layout_fragment_sub_audio_level = 0x7f030002;
        public static final int layout_fragment_sub_control = 0x7f030003;
        public static final int layout_fragment_sub_quality = 0x7f030004;
        public static final int layout_ui_activity = 0x7f030005;
        public static final int main_activity = 0x7f030006;
        public static final int main_layout = 0x7f030007;
        public static final int room = 0x7f030008;
        public static final int voice_only_layout = 0x7f030009;
        public static final int voice_row = 0x7f03000a;
    }

    public static final class menu {
        public static final int activity_main = 0x7f070000;
    }

    public static final class string {
        public static final int app_name = 0x7f050000;
        public static final int archivingOff = 0x7f050001;
        public static final int archivingOn = 0x7f050002;
        public static final int audioOnly = 0x7f050003;
        public static final int audiodevice = 0x7f050004;
        public static final int clearNotificationService = 0x7f050005;
        public static final int endCall1 = 0x7f050006;
        public static final int endCall2 = 0x7f050007;
        public static final int helloworld = 0x7f050008;
        public static final int helloworldcapturer = 0x7f050009;
        public static final int helloworldemulator = 0x7f05000a;
        public static final int helloworldrenderer = 0x7f05000b;
        public static final int helloworldsubclassing = 0x7f05000c;
        public static final int helloworldui = 0x7f05000d;
        public static final int menu_settings = 0x7f05000e;
        public static final int notification = 0x7f05000f;
        public static final int send = 0x7f050010;
        public static final int swapStr = 0x7f050011;
        public static final int voinceonly = 0x7f050012;
    }

    public static final class style {
        /**
         * Theme customizations available in newer API levels can go in
         * res/values-vXX/styles.xml, while customizations related to
         * backward-compatibility can go here.
         * <p/>
         * API 11 theme customizations can go here.
         * API 14 theme customizations can go here.
         */
        public static final int AppBaseTheme = 0x7f060000;
        /**
         * All customizations that are NOT specific to a particular API-level can go here.
         */
        public static final int AppTheme = 0x7f060001;
    }
}
